server:
  servlet:
    context-path: /
  port: 8080

logging:
  level:
    com.oasm.service: INFO
    com.oasm.dao.RegisterStatusDAO: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: TRACE

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mariadb://192.168.11.201:3307/oasm?characterEncoding=UTF-8
    username: root
    password: sug123$%^
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
  mapper-locations: /static/mappers/*.xml